language: node_js
node_js:
- '6.1'
install:
- npm install
before_deploy:
- npm run build
deploy:
  provider: s3
  skip_cleanup: true
  secret_access_key:
    secure: "DOTOpSUx1TPNcue8qlr4dsU13FByuyXqN/EL09TYWrrpKt+ouiDo/XznIVEU5k7mX/cgW3nLx2cm3ud4VBU8/T+s+fZYdvfgtyjx+t6s1k2/dt6T9Vk+kM9gUVdE7C9883mro3qSp2CFIlCRWLHuqKVJJxu/h360RORpSnssYpC8dxxe9FIiST4YJeN/Q6JeJyPP4YUuhPXgYNkxVKIvHgCs0AbmmRe9VDIZfkkESYcxsMF2Btwu8AKOBbLM5phjEUrRGI0xV5syrCQBZ4RNkrxQmCPgUgWlwXStiAK8Gjb0f242uBGUC4qU5j7RAXDvhFb/hTZnZSF6xzyDiojVoYEX9pGR0dRfPv4rDm2ZhIzam4YtVexCH1yf4XlUf+l6T3Wj3NmHgRi4boLpApgG7W/ZmXzApqQsOlOe4vFRw5V0mxU4LNSPOVCDsVIYZOYoQsqtH1ky8qYNxVaxpSI88XJxRfDLHvCm2oucfWtUJODXMiV43iu3TXRU4tBpibK+/YPvWNdc1Ky5tpk3eLuZNZQn1Cx51I/j2CP5SiuZTqdpHk7tsbmXPJP+PGmDc2HSa7cuUediFhqD4GTK2DtwBmGeNpz7DUrmqY3oz3hSt3yW6xTVKFPpN2VjFkYmaeT7sIf49ru0Ow9AD11R1LRadjMHWh/OFrcVS6Z/pjo6LqA="
  access_key_id:
    secure: "E8kBs+pMazP4PxPDtV8lq9R7QIzTl8O8g2eptI+UcHLv77si+n71sjXH5WXreshwfe7JyboExrtkTZSTuHhKAJtw7+oAsbvOrvOAD2UC3dDt4ejJWY7xbMXiuWAo1cDQaoKLuZhV16DEmiNslTjXejLiPtPSPRnTnn8wUOKuRb1Mx+UVI0+GKLt3WVj5W5LQFmkwlYIdX0ux8HLIT7YPWLbLdJEkoBWSsP6K1L1p4FBDMN+7rLhw+dayHhbsRDaxr7xzVZo1koI5MUHpvXgzHjJA/iTsw6MR5wNQahM6+wnTG5mOBKJIxSvAQPSaaOATNIMdwdrUl6GcNjYEw1Hgq++chBtB7DMwcio+6HmAIz9QTYUJLRLe9cOOoqMsfVoX8QGdHId3z23q3j2PmEA4dxbUsgdJn4e8hRsTKtnSTyJ5uvWx1jJjVh1lYECuPGtmbYOPF6mZHVb9GHDSdTzQnhZYryQfD0VqLGQAPOy5ODLmuKSAG4rVs+zvPEzNgZSLPTqGzwfgr9d52hXgOv8ztW0ucHupH/7WD62+lIh3hHHoN+bsornwSQYzBLxRBfOKqXR1rjFKFhw+aqZndbKLwR63L2qQJCJYzK0hiYj8v9mIiFTmlS22XAOVmfkBv3x47lfklIMCJgXoBMJ0NaltsD7l4Hf9GxhMAHZkJvCC1jE="
  bucket: frontend.on
  region: eu-central-1
  local_dir: public
  on:
    branch: test-deploy
    repo: olegnikitashin/spa_frontend
