export const ADD_POST_SUCCESS = 'ADD_POST_SUCCESS';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const SHOW_POST_SUCCESS = 'SHOW_POST_SUCCESS';
export const BUTTON_ENABLED = 'BUTTON_ENABLED';
export const BUTTON_DISABLED = 'BUTTON_DISABLED';
